//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Utility;

namespace MakerShop.Products
{
    /// <summary>
    /// DataSource class for KitProduct objects
    /// </summary>
    public partial class KitProductDataSource
    {
        /// <summary>
        /// Deletes a KitProduct object from the database
        /// </summary>
        /// <param name="kitProduct">The KitProduct object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(KitProduct kitProduct)
        {
            return kitProduct.Delete();
        }

        /// <summary>
        /// Deletes a KitProduct object with given id from the database
        /// </summary>
        /// <param name="kitProductId">Value of KitProductId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 kitProductId)
        {
            KitProduct kitProduct = new KitProduct();
            if (kitProduct.Load(kitProductId)) return kitProduct.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a KitProduct object to the database.
        /// </summary>
        /// <param name="kitProduct">The KitProduct object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(KitProduct kitProduct) { return kitProduct.Save(); }

        /// <summary>
        /// Loads a KitProduct object for given Id from the database.
        /// </summary>
        /// <param name="kitProductId">Value of KitProductId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded KitProduct object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProduct Load(Int32 kitProductId)
        {
            return KitProductDataSource.Load(kitProductId, true);
        }

        /// <summary>
        /// Loads a KitProduct object for given Id from the database.
        /// </summary>
        /// <param name="kitProductId">Value of KitProductId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded KitProduct object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProduct Load(Int32 kitProductId, bool useCache)
        {
            if (kitProductId == 0) return null;
            KitProduct kitProduct = null;
            string key = "KitProduct_" + kitProductId.ToString();
            if (useCache)
            {
                kitProduct = ContextCache.GetObject(key) as KitProduct;
                if (kitProduct != null) return kitProduct;
            }
            kitProduct = new KitProduct();
            if (kitProduct.Load(kitProductId))
            {
                if (useCache) ContextCache.SetObject(key, kitProduct);
                return kitProduct;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of KitProduct objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the KitProduct objects that should be loaded.</param>
        /// <returns>The number of KitProduct objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_KitProducts" + whereClause);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of KitProduct objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + KitProduct.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_KitProducts");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            KitProductCollection results = new KitProductCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        KitProduct kitProduct = new KitProduct();
                        KitProduct.LoadDataReader(kitProduct, dr);
                        results.Add(kitProduct);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of KitProduct objects for the given KitComponentId in the database.
        /// <param name="kitComponentId">The given KitComponentId</param>
        /// </summary>
        /// <returns>The Number of KitProduct objects for the given KitComponentId in the database.</returns>
        public static int CountForKitComponent(Int32 kitComponentId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_KitProducts WHERE KitComponentId = @kitComponentId");
            database.AddInParameter(selectCommand, "@kitComponentId", System.Data.DbType.Int32, kitComponentId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of KitProduct objects for the given KitComponentId from the database
        /// </summary>
        /// <param name="kitComponentId">The given KitComponentId</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForKitComponent(Int32 kitComponentId)
        {
            return LoadForKitComponent(kitComponentId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects for the given KitComponentId from the database
        /// </summary>
        /// <param name="kitComponentId">The given KitComponentId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForKitComponent(Int32 kitComponentId, string sortExpression)
        {
            return LoadForKitComponent(kitComponentId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects for the given KitComponentId from the database
        /// </summary>
        /// <param name="kitComponentId">The given KitComponentId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForKitComponent(Int32 kitComponentId, int maximumRows, int startRowIndex)
        {
            return LoadForKitComponent(kitComponentId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of KitProduct objects for the given KitComponentId from the database
        /// </summary>
        /// <param name="kitComponentId">The given KitComponentId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of KitProduct objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static KitProductCollection LoadForKitComponent(Int32 kitComponentId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + KitProduct.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_KitProducts");
            selectQuery.Append(" WHERE KitComponentId = @kitComponentId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@kitComponentId", System.Data.DbType.Int32, kitComponentId);
            //EXECUTE THE COMMAND
            KitProductCollection results = new KitProductCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        KitProduct kitProduct = new KitProduct();
                        KitProduct.LoadDataReader(kitProduct, dr);
                        results.Add(kitProduct);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Gets the next value of the OrderBy field for KitProduct objects.
        /// </summary>
        /// <param name="kitComponentId">The KitComponentId for which to get the next OrderBy value</param>
        /// <returns>The next value of the OrderBy field for KitProduct objects</returns>
        public static short GetNextOrderBy(Int32 kitComponentId)
        {
            Database database = Token.Instance.Database;
            using (DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT (Max(OrderBy) + 1) AS NextOrderBy FROM ac_KitProducts WHERE KitComponentId = @kitComponentId"))
            {
                database.AddInParameter(selectCommand, "@kitComponentId", System.Data.DbType.Int32, kitComponentId);
                object result = database.ExecuteScalar(selectCommand);
                if (result.Equals(DBNull.Value)) return 1;
                return (short)(int)result;
            }
        }

        /// <summary>
        /// Updates/Saves the given KitProduct object to the database.
        /// </summary>
        /// <param name="kitProduct">The KitProduct object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(KitProduct kitProduct) { return kitProduct.Save(); }

    }
}
