//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Products;
using MakerShop.Utility;

namespace MakerShop.Products
{
    /// <summary>
    /// This class represents a ProductTemplateField object in the database.
    /// </summary>
    public partial class ProductTemplateField : IPersistable
    {

#region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public ProductTemplateField() { }

        /// <summary>
        /// Constructor with primary key
        /// <param name="productTemplateFieldId">Value of ProductTemplateFieldId.</param>
        /// </summary>
        public ProductTemplateField(Int32 productTemplateFieldId)
        {
            this.ProductTemplateFieldId = productTemplateFieldId;
        }

        /// <summary>
        /// Returns a coma separated list of column names in this database object.
        /// </summary>
        /// <param name="prefix">Prefix to use with column names. Leave null or empty for no prefix.</param>
        /// <returns>A coman separated list of column names for this database object.</returns>
        public static string GetColumnNames(string prefix)
        {
          if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
          else prefix = prefix + ".";
          List<string> columnNames = new List<string>();
          columnNames.Add(prefix + "ProductTemplateFieldId");
          columnNames.Add(prefix + "ProductId");
          columnNames.Add(prefix + "InputFieldId");
          columnNames.Add(prefix + "InputValue");
          return string.Join(",", columnNames.ToArray());
        }

        /// <summary>
        /// Loads the given ProductTemplateField object from the given database data reader.
        /// </summary>
        /// <param name="productTemplateField">The ProductTemplateField object to load.</param>
        /// <param name="dr">The database data reader to read data from.</param>
        public static void LoadDataReader(ProductTemplateField productTemplateField, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA
            productTemplateField.ProductTemplateFieldId = dr.GetInt32(0);
            productTemplateField.ProductId = dr.GetInt32(1);
            productTemplateField.InputFieldId = dr.GetInt32(2);
            productTemplateField.InputValue = dr.GetString(3);
            productTemplateField.IsDirty = false;
        }

#endregion

        private Int32 _ProductTemplateFieldId;
        private Int32 _ProductId;
        private Int32 _InputFieldId;
        private String _InputValue = string.Empty;
        private bool _IsDirty;

        /// <summary>
        /// ProductTemplateFieldId
        /// </summary>
        [DataObjectField(true, true, false)]
        public Int32 ProductTemplateFieldId
        {
            get { return this._ProductTemplateFieldId; }
            set
            {
                if (this._ProductTemplateFieldId != value)
                {
                    this._ProductTemplateFieldId = value;
                    this.IsDirty = true;
                }
            }
        }

        /// <summary>
        /// ProductId
        /// </summary>
        public Int32 ProductId
        {
            get { return this._ProductId; }
            set
            {
                if (this._ProductId != value)
                {
                    this._ProductId = value;
                    this.IsDirty = true;
                    this._Product = null;
                }
            }
        }

        /// <summary>
        /// InputFieldId
        /// </summary>
        public Int32 InputFieldId
        {
            get { return this._InputFieldId; }
            set
            {
                if (this._InputFieldId != value)
                {
                    this._InputFieldId = value;
                    this.IsDirty = true;
                    this._InputField = null;
                }
            }
        }

        /// <summary>
        /// InputValue
        /// </summary>
        public String InputValue
        {
            get { return this._InputValue; }
            set
            {
                if (this._InputValue != value)
                {
                    this._InputValue = value;
                    this.IsDirty = true;
                }
            }
        }

        /// <summary>
        /// Indicates whether this ProductTemplateField object has changed since it was loaded from the database.
        /// </summary>
        public bool IsDirty
        {
            get { return this._IsDirty; }
            set { this._IsDirty = value; }
        }

#region Parents
        private InputField _InputField;
        private Product _Product;

        /// <summary>
        /// The InputField object that this ProductTemplateField object is associated with
        /// </summary>
        public InputField InputField
        {
            get
            {
                if (!this.InputFieldLoaded)
                {
                    this._InputField = InputFieldDataSource.Load(this.InputFieldId);
                }
                return this._InputField;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool InputFieldLoaded { get { return ((this._InputField != null) && (this._InputField.InputFieldId == this.InputFieldId)); } }

        /// <summary>
        /// The Product object that this ProductTemplateField object is associated with
        /// </summary>
        public Product Product
        {
            get
            {
                if (!this.ProductLoaded)
                {
                    this._Product = ProductDataSource.Load(this.ProductId);
                }
                return this._Product;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool ProductLoaded { get { return ((this._Product != null) && (this._Product.ProductId == this.ProductId)); } }

#endregion

        /// <summary>
        /// Deletes this ProductTemplateField object from the database.
        /// </summary>
        /// <returns><b>true</b> if delete successful, <b>false</b> otherwise.</returns>
        public virtual bool Delete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM ac_ProductTemplateFields");
            deleteQuery.Append(" WHERE ProductTemplateFieldId = @productTemplateFieldId");
            Database database = Token.Instance.Database;

            MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {
                database.AddInParameter(deleteCommand, "@ProductTemplateFieldId", System.Data.DbType.Int32, this.ProductTemplateFieldId);
                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }

            MakerShop.Stores.AuditEventDataSource.AuditInfoEnd();

            return (recordsAffected > 0);
        }


        /// <summary>
        /// Load this ProductTemplateField object from the database for the given primary key.
        /// </summary>
        /// <param name="productTemplateFieldId">Value of ProductTemplateFieldId of the object to load.</param>
        /// <returns><b>true</b> if load is successful, <b>false</b> otherwise</returns>
        public virtual bool Load(Int32 productTemplateFieldId)
        {
            bool result = false;
            this.ProductTemplateFieldId = productTemplateFieldId;
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT " + GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_ProductTemplateFields");
            selectQuery.Append(" WHERE ProductTemplateFieldId = @productTemplateFieldId");
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@productTemplateFieldId", System.Data.DbType.Int32, productTemplateFieldId);
            //EXECUTE THE COMMAND
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                if (dr.Read())
                {
                    result = true;
                    LoadDataReader(this, dr);;
                }
                dr.Close();
            }
            return result;
        }

        /// <summary>
        /// Saves this ProductTemplateField object to the database.
        /// </summary>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
                bool recordExists = true;
                
                if (this.ProductTemplateFieldId == 0) recordExists = false;

                if (recordExists) {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) As RecordCount FROM ac_ProductTemplateFields");
                    selectQuery.Append(" WHERE ProductTemplateFieldId = @productTemplateFieldId");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {
                        database.AddInParameter(selectCommand, "@ProductTemplateFieldId", System.Data.DbType.Int32, this.ProductTemplateFieldId);
                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                int result = 0;
                if (recordExists)
                {
                    //UPDATE
                    StringBuilder updateQuery = new StringBuilder();
                    updateQuery.Append("UPDATE ac_ProductTemplateFields SET ");
                    updateQuery.Append("ProductId = @ProductId");
                    updateQuery.Append(", InputFieldId = @InputFieldId");
                    updateQuery.Append(", InputValue = @InputValue");
                    updateQuery.Append(" WHERE ProductTemplateFieldId = @ProductTemplateFieldId");
                    using (DbCommand updateCommand = database.GetSqlStringCommand(updateQuery.ToString()))
                    {
                        database.AddInParameter(updateCommand, "@ProductTemplateFieldId", System.Data.DbType.Int32, this.ProductTemplateFieldId);
                        database.AddInParameter(updateCommand, "@ProductId", System.Data.DbType.Int32, this.ProductId);
                        database.AddInParameter(updateCommand, "@InputFieldId", System.Data.DbType.Int32, this.InputFieldId);
                        database.AddInParameter(updateCommand, "@InputValue", System.Data.DbType.String, this.InputValue);
                        //RESULT IS NUMBER OF RECORDS AFFECTED
                        result = database.ExecuteNonQuery(updateCommand);
                    }
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO ac_ProductTemplateFields (ProductId, InputFieldId, InputValue)");
                    insertQuery.Append(" VALUES (@ProductId, @InputFieldId, @InputValue)");
                    insertQuery.Append("; SELECT Scope_Identity()");
                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {
                        database.AddInParameter(insertCommand, "@ProductTemplateFieldId", System.Data.DbType.Int32, this.ProductTemplateFieldId);
                        database.AddInParameter(insertCommand, "@ProductId", System.Data.DbType.Int32, this.ProductId);
                        database.AddInParameter(insertCommand, "@InputFieldId", System.Data.DbType.Int32, this.InputFieldId);
                        database.AddInParameter(insertCommand, "@InputValue", System.Data.DbType.String, this.InputValue);
                        //RESULT IS NEW IDENTITY;
                        result = AlwaysConvert.ToInt(database.ExecuteScalar(insertCommand));
                        this._ProductTemplateFieldId = result;
                    }
                }
                MakerShop.Stores.AuditEventDataSource.AuditInfoEnd(); 
                //OBJECT IS DIRTY IF NO RECORDS WERE UPDATED OR INSERTED
                this.IsDirty = (result == 0);
                if (this.IsDirty) { return SaveResult.Failed; }
                else { return (recordExists ? SaveResult.RecordUpdated : SaveResult.RecordInserted); }
            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

     }
}
