//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Utility;

namespace MakerShop.Products
{
    /// <summary>
    /// DataSource class for WrapStyle objects
    /// </summary>
    public partial class WrapStyleDataSource
    {
        /// <summary>
        /// Deletes a WrapStyle object from the database
        /// </summary>
        /// <param name="wrapStyle">The WrapStyle object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(WrapStyle wrapStyle)
        {
            return wrapStyle.Delete();
        }

        /// <summary>
        /// Deletes a WrapStyle object with given id from the database
        /// </summary>
        /// <param name="wrapStyleId">Value of WrapStyleId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 wrapStyleId)
        {
            WrapStyle wrapStyle = new WrapStyle();
            if (wrapStyle.Load(wrapStyleId)) return wrapStyle.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a WrapStyle object to the database.
        /// </summary>
        /// <param name="wrapStyle">The WrapStyle object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(WrapStyle wrapStyle) { return wrapStyle.Save(); }

        /// <summary>
        /// Loads a WrapStyle object for given Id from the database.
        /// </summary>
        /// <param name="wrapStyleId">Value of WrapStyleId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded WrapStyle object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyle Load(Int32 wrapStyleId)
        {
            return WrapStyleDataSource.Load(wrapStyleId, true);
        }

        /// <summary>
        /// Loads a WrapStyle object for given Id from the database.
        /// </summary>
        /// <param name="wrapStyleId">Value of WrapStyleId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded WrapStyle object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyle Load(Int32 wrapStyleId, bool useCache)
        {
            if (wrapStyleId == 0) return null;
            WrapStyle wrapStyle = null;
            string key = "WrapStyle_" + wrapStyleId.ToString();
            if (useCache)
            {
                wrapStyle = ContextCache.GetObject(key) as WrapStyle;
                if (wrapStyle != null) return wrapStyle;
            }
            wrapStyle = new WrapStyle();
            if (wrapStyle.Load(wrapStyleId))
            {
                if (useCache) ContextCache.SetObject(key, wrapStyle);
                return wrapStyle;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of WrapStyle objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the WrapStyle objects that should be loaded.</param>
        /// <returns>The number of WrapStyle objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_WrapStyles" + whereClause);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + WrapStyle.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_WrapStyles");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            WrapStyleCollection results = new WrapStyleCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        WrapStyle wrapStyle = new WrapStyle();
                        WrapStyle.LoadDataReader(wrapStyle, dr);
                        results.Add(wrapStyle);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of WrapStyle objects for the given TaxCodeId in the database.
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// </summary>
        /// <returns>The Number of WrapStyle objects for the given TaxCodeId in the database.</returns>
        public static int CountForTaxCode(Int32 taxCodeId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_WrapStyles WHERE TaxCodeId = @taxCodeId");
            database.AddInParameter(selectCommand, "@taxCodeId", System.Data.DbType.Int32, NullableData.DbNullify(taxCodeId));
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForTaxCode(Int32 taxCodeId)
        {
            return LoadForTaxCode(taxCodeId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForTaxCode(Int32 taxCodeId, string sortExpression)
        {
            return LoadForTaxCode(taxCodeId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForTaxCode(Int32 taxCodeId, int maximumRows, int startRowIndex)
        {
            return LoadForTaxCode(taxCodeId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForTaxCode(Int32 taxCodeId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + WrapStyle.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_WrapStyles");
            selectQuery.Append(" WHERE TaxCodeId = @taxCodeId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@taxCodeId", System.Data.DbType.Int32, NullableData.DbNullify(taxCodeId));
            //EXECUTE THE COMMAND
            WrapStyleCollection results = new WrapStyleCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        WrapStyle wrapStyle = new WrapStyle();
                        WrapStyle.LoadDataReader(wrapStyle, dr);
                        results.Add(wrapStyle);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of WrapStyle objects for the given WrapGroupId in the database.
        /// <param name="wrapGroupId">The given WrapGroupId</param>
        /// </summary>
        /// <returns>The Number of WrapStyle objects for the given WrapGroupId in the database.</returns>
        public static int CountForWrapGroup(Int32 wrapGroupId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_WrapStyles WHERE WrapGroupId = @wrapGroupId");
            database.AddInParameter(selectCommand, "@wrapGroupId", System.Data.DbType.Int32, wrapGroupId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given WrapGroupId from the database
        /// </summary>
        /// <param name="wrapGroupId">The given WrapGroupId</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForWrapGroup(Int32 wrapGroupId)
        {
            return LoadForWrapGroup(wrapGroupId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given WrapGroupId from the database
        /// </summary>
        /// <param name="wrapGroupId">The given WrapGroupId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForWrapGroup(Int32 wrapGroupId, string sortExpression)
        {
            return LoadForWrapGroup(wrapGroupId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given WrapGroupId from the database
        /// </summary>
        /// <param name="wrapGroupId">The given WrapGroupId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForWrapGroup(Int32 wrapGroupId, int maximumRows, int startRowIndex)
        {
            return LoadForWrapGroup(wrapGroupId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of WrapStyle objects for the given WrapGroupId from the database
        /// </summary>
        /// <param name="wrapGroupId">The given WrapGroupId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of WrapStyle objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static WrapStyleCollection LoadForWrapGroup(Int32 wrapGroupId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + WrapStyle.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_WrapStyles");
            selectQuery.Append(" WHERE WrapGroupId = @wrapGroupId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@wrapGroupId", System.Data.DbType.Int32, wrapGroupId);
            //EXECUTE THE COMMAND
            WrapStyleCollection results = new WrapStyleCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        WrapStyle wrapStyle = new WrapStyle();
                        WrapStyle.LoadDataReader(wrapStyle, dr);
                        results.Add(wrapStyle);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Gets the next value of the OrderBy field for WrapStyle objects.
        /// </summary>
        /// <param name="wrapGroupId">The WrapGroupId for which to get the next OrderBy value</param>
        /// <returns>The next value of the OrderBy field for WrapStyle objects</returns>
        public static short GetNextOrderBy(Int32 wrapGroupId)
        {
            Database database = Token.Instance.Database;
            using (DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT (Max(OrderBy) + 1) AS NextOrderBy FROM ac_WrapStyles WHERE WrapGroupId = @wrapGroupId"))
            {
                database.AddInParameter(selectCommand, "@wrapGroupId", System.Data.DbType.Int32, wrapGroupId);
                object result = database.ExecuteScalar(selectCommand);
                if (result.Equals(DBNull.Value)) return 1;
                return (short)(int)result;
            }
        }

        /// <summary>
        /// Updates/Saves the given WrapStyle object to the database.
        /// </summary>
        /// <param name="wrapStyle">The WrapStyle object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(WrapStyle wrapStyle) { return wrapStyle.Save(); }

    }
}
