//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Utility;

namespace MakerShop.Messaging
{
    /// <summary>
    /// DataSource class for EmailTemplate objects
    /// </summary>
    public partial class EmailTemplateDataSource
    {
        /// <summary>
        /// Deletes a EmailTemplate object from the database
        /// </summary>
        /// <param name="emailTemplate">The EmailTemplate object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(EmailTemplate emailTemplate)
        {
            return emailTemplate.Delete();
        }

        /// <summary>
        /// Deletes a EmailTemplate object with given id from the database
        /// </summary>
        /// <param name="emailTemplateId">Value of EmailTemplateId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 emailTemplateId)
        {
            EmailTemplate emailTemplate = new EmailTemplate();
            if (emailTemplate.Load(emailTemplateId)) return emailTemplate.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a EmailTemplate object to the database.
        /// </summary>
        /// <param name="emailTemplate">The EmailTemplate object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(EmailTemplate emailTemplate) { return emailTemplate.Save(); }

        /// <summary>
        /// Loads a EmailTemplate object for given Id from the database.
        /// </summary>
        /// <param name="emailTemplateId">Value of EmailTemplateId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded EmailTemplate object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplate Load(Int32 emailTemplateId)
        {
            return EmailTemplateDataSource.Load(emailTemplateId, true);
        }

        /// <summary>
        /// Loads a EmailTemplate object for given Id from the database.
        /// </summary>
        /// <param name="emailTemplateId">Value of EmailTemplateId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded EmailTemplate object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplate Load(Int32 emailTemplateId, bool useCache)
        {
            if (emailTemplateId == 0) return null;
            EmailTemplate emailTemplate = null;
            string key = "EmailTemplate_" + emailTemplateId.ToString();
            if (useCache)
            {
                emailTemplate = ContextCache.GetObject(key) as EmailTemplate;
                if (emailTemplate != null) return emailTemplate;
            }
            emailTemplate = new EmailTemplate();
            if (emailTemplate.Load(emailTemplateId))
            {
                if (useCache) ContextCache.SetObject(key, emailTemplate);
                return emailTemplate;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of EmailTemplate objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the EmailTemplate objects that should be loaded.</param>
        /// <returns>The number of EmailTemplate objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_EmailTemplates" + whereClause);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailTemplate.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailTemplates");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            EmailTemplateCollection results = new EmailTemplateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailTemplate emailTemplate = new EmailTemplate();
                        EmailTemplate.LoadDataReader(emailTemplate, dr);
                        results.Add(emailTemplate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of EmailTemplate objects associated with the given OrderStatusId
        /// </summary>
        /// <param name="orderStatusId">The given OrderStatusId</param>
        /// <returns>The number of EmailTemplate objects associated with with the given OrderStatusId</returns>
        public static int CountForOrderStatus(Int32 orderStatusId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_OrderStatusEmails WHERE OrderStatusId = @orderStatusId");
            database.AddInParameter(selectCommand, "@orderStatusId", System.Data.DbType.Int32, orderStatusId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }
        /// <summary>
        /// Loads the EmailTemplate objects associated with the given OrderStatusId
        /// </summary>
        /// <param name="orderStatusId">The given OrderStatusId</param>
        /// <returns>A collection of EmailTemplate objects associated with with the given OrderStatusId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForOrderStatus(Int32 orderStatusId)
        {
            return EmailTemplateDataSource.LoadForOrderStatus(orderStatusId, 0, 0, string.Empty);
        }
        /// <summary>
        /// Loads the EmailTemplate objects associated with the given OrderStatusId
        /// </summary>
        /// <param name="orderStatusId">The given OrderStatusId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects associated with with the given OrderStatusId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForOrderStatus(Int32 orderStatusId, string sortExpression)
        {
            return EmailTemplateDataSource.LoadForOrderStatus(orderStatusId, 0, 0, sortExpression);
        }
        /// <summary>
        /// Loads the EmailTemplate objects associated with the given OrderStatusId
        /// </summary>
        /// <param name="orderStatusId">The given OrderStatusId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailTemplate objects associated with with the given OrderStatusId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForOrderStatus(Int32 orderStatusId, int maximumRows, int startRowIndex)
        {
            return EmailTemplateDataSource.LoadForOrderStatus(orderStatusId, maximumRows, startRowIndex, string.Empty);
        }
        /// <summary>
        /// Loads the EmailTemplate objects associated with the given OrderStatusId
        /// </summary>
        /// <param name="orderStatusId">The given OrderStatusId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects associated with with the given OrderStatusId</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForOrderStatus(Int32 orderStatusId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailTemplate.GetColumnNames("ac_EmailTemplates"));
            selectQuery.Append(" FROM ac_EmailTemplates, ac_OrderStatusEmails");
            selectQuery.Append(" WHERE ac_EmailTemplates.EmailTemplateId = ac_OrderStatusEmails.EmailTemplateId");
            selectQuery.Append(" AND ac_OrderStatusEmails.OrderStatusId = @orderStatusId");
            selectQuery.Append(" AND StoreId = @storeId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@orderStatusId", System.Data.DbType.Int32, orderStatusId);
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, Token.Instance.StoreId);
            //EXECUTE THE COMMAND
            EmailTemplateCollection results = new EmailTemplateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailTemplate emailTemplate = new EmailTemplate();
                        EmailTemplate.LoadDataReader(emailTemplate, dr);
                        results.Add(emailTemplate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of EmailTemplate objects for the current store.
        /// </summary>
        /// <returns>The Number of EmailTemplate objects in the current store.</returns>
        public static int CountForStore()
        {
            int storeId = Token.Instance.StoreId;
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_EmailTemplates WHERE StoreId = @storeId");
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects for the current store from the database
        /// </summary>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForStore()
        {
            return LoadForStore(0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForStore(string sortExpression)
        {
            return LoadForStore(0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects for the current store from the database.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForStore(int maximumRows, int startRowIndex)
        {
            return LoadForStore(maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of EmailTemplate objects for the current store from the database. Sorts using the given sort exrpression.
        /// </summary>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of EmailTemplate objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateCollection LoadForStore(int maximumRows, int startRowIndex, string sortExpression)
        {
            int storeId = Token.Instance.StoreId;
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailTemplate.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_EmailTemplates");
            selectQuery.Append(" WHERE StoreId = @storeId");
            if (!string.IsNullOrEmpty(sortExpression)) selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@storeId", System.Data.DbType.Int32, storeId);
            //EXECUTE THE COMMAND
            EmailTemplateCollection results = new EmailTemplateCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailTemplate emailTemplate = new EmailTemplate();
                        EmailTemplate.LoadDataReader(emailTemplate, dr);
                        results.Add(emailTemplate);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Updates/Saves the given EmailTemplate object to the database.
        /// </summary>
        /// <param name="emailTemplate">The EmailTemplate object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(EmailTemplate emailTemplate) { return emailTemplate.Save(); }

    }
}
