//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Utility;

namespace MakerShop.Messaging
{
    public partial class EmailTemplateTrigger_CatalogDataSource
    {
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(EmailTemplateTrigger_Catalog pEmailTemplateTriggers_Catalog)
        {
            return pEmailTemplateTriggers_Catalog.Delete();
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 pEmailTemplateId, Int32 pStoreEventId, Byte pCatalogNodeTypeId, Int32 pCatalogNodeId, Int16 pPaymentTypeId)
        {
            EmailTemplateTrigger_Catalog varEmailTemplateTriggers_Catalog = new EmailTemplateTrigger_Catalog();
            if (varEmailTemplateTriggers_Catalog.Load(pEmailTemplateId, pStoreEventId, pCatalogNodeTypeId, pCatalogNodeId, pPaymentTypeId)) return varEmailTemplateTriggers_Catalog.Delete();
            return false;
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(EmailTemplateTrigger_Catalog pEmailTemplateTriggers_Catalog) { return pEmailTemplateTriggers_Catalog.Save(); }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateTrigger_Catalog Load(Int32 pEmailTemplateId, Int32 pStoreEventId, Byte pCatalogNodeTypeId, Int32 pCatalogNodeId, Int16 pPaymentTypeId)
        {
            EmailTemplateTrigger_Catalog varEmailTemplateTriggers_Catalog = new EmailTemplateTrigger_Catalog();
            if (varEmailTemplateTriggers_Catalog.Load(pEmailTemplateId, pStoreEventId, pCatalogNodeTypeId, pCatalogNodeId, pPaymentTypeId)) return varEmailTemplateTriggers_Catalog;
            return null;
        }

        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM xm_EmailTemplateTriggers_Catalog" + whereClause);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateTrigger_CatalogCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateTrigger_CatalogCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateTrigger_CatalogCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static EmailTemplateTrigger_CatalogCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            //if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + EmailTemplateTrigger_Catalog.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM xm_EmailTemplateTriggers_Catalog");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            if (!string.IsNullOrEmpty(sortExpression)) 
                selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            EmailTemplateTrigger_CatalogCollection results = new EmailTemplateTrigger_CatalogCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        EmailTemplateTrigger_Catalog varEmailTemplateTriggers_Catalog = new EmailTemplateTrigger_Catalog();
                        EmailTemplateTrigger_Catalog.LoadDataReader(varEmailTemplateTriggers_Catalog, dr);
                        results.Add(varEmailTemplateTriggers_Catalog);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(EmailTemplateTrigger_Catalog pEmailTemplateTriggers_Catalog) { return pEmailTemplateTriggers_Catalog.Save(); }
    }
}

