//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Payments;
using MakerShop.Stores;
using MakerShop.Utility;

namespace MakerShop.Payments
{
    public partial class PaymentGatewayTemplate : IPersistable
    {

        #region Constructors

        public PaymentGatewayTemplate() { }

        public PaymentGatewayTemplate(Int32 pPaymentGatewayTemplateId)
        {
            this.PaymentGatewayTemplateId = pPaymentGatewayTemplateId;

        }

        public static string GetColumnNames(string prefix)
        {
            if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
            else prefix = prefix + ".";
            List<string> columnNames = new List<string>();
            columnNames.Add(prefix + "PaymentGatewayTemplateId");
            columnNames.Add(prefix + "Name");


            return string.Join(",", columnNames.ToArray());
        }

        public static void LoadDataReader(PaymentGatewayTemplate pPaymentGatewayTemplates, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA

            pPaymentGatewayTemplates.PaymentGatewayTemplateId = dr.GetInt32(0);

            pPaymentGatewayTemplates.Name = dr.GetString(1);


            pPaymentGatewayTemplates.IsDirty = false;
        }

        #endregion

        #region Class Data

        private bool _IsDirty;

        public bool IsDirty
        {
            get { return this._IsDirty; }
            set { this._IsDirty = value; }
        }


        private Int32 _PaymentGatewayTemplateId;

        [DataObjectField(true, false, false)]
        public Int32 PaymentGatewayTemplateId
        {
            get { return this._PaymentGatewayTemplateId; }
            set
            {
                if (this._PaymentGatewayTemplateId != value)
                {
                    this._PaymentGatewayTemplateId = value;
                    this.IsDirty = true;
                }
            }
        }


        private String _Name;

        [DataObjectField(true, false, false)]
        public String Name
        {
            get { return this._Name; }
            set
            {
                if (this._Name != value)
                {
                    this._Name = value;
                    this.IsDirty = true;
                }
            }
        }



        #endregion



        #region CURD

        public virtual bool Delete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM xm_PaymentGatewayTemplates");
            deleteQuery.Append(" WHERE  PaymentGatewayTemplateId = @PaymentGatewayTemplateId  ");
            Database database = Token.Instance.Database;

            MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {

                database.AddInParameter(deleteCommand, "@PaymentGatewayTemplateId", System.Data.DbType.Int32, this.PaymentGatewayTemplateId);

                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }
            MakerShop.Stores.AuditEventDataSource.AuditInfoEnd();
            return (recordsAffected > 0);
        }

        public virtual bool Load(Int32 pPaymentGatewayTemplateId)
        {
            bool result = false;

            this.PaymentGatewayTemplateId = pPaymentGatewayTemplateId;


            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT " + GetColumnNames(string.Empty));
            selectQuery.Append(" FROM xm_PaymentGatewayTemplates");
            selectQuery.Append(" WHERE  PaymentGatewayTemplateId = @PaymentGatewayTemplateId  ");
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());


            database.AddInParameter(selectCommand, "@PaymentGatewayTemplateId", System.Data.DbType.Int32, this.PaymentGatewayTemplateId);


            //EXECUTE THE COMMAND
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                if (dr.Read())
                {
                    result = true;
                    LoadDataReader(this, dr); ;
                }
                dr.Close();
            }
            return result;
        }

        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
                bool recordExists = true;

                if (recordExists)
                {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) As RecordCount FROM xm_PaymentGatewayTemplates");
                    selectQuery.Append(" WHERE  PaymentGatewayTemplateId = @PaymentGatewayTemplateId ");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {

                        database.AddInParameter(selectCommand, "@PaymentGatewayTemplateId", System.Data.DbType.Int32, this.PaymentGatewayTemplateId);


                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                int result = 0;
                if (recordExists)
                {
                    //UPDATE
                    StringBuilder updateQuery = new StringBuilder();
                    updateQuery.Append("UPDATE xm_PaymentGatewayTemplates SET ");

                    updateQuery.Append("Name = @Name");

                    updateQuery.Append(" WHERE  PaymentGatewayTemplateId = @PaymentGatewayTemplateId ");
                    using (DbCommand updateCommand = database.GetSqlStringCommand(updateQuery.ToString()))
                    {


                        database.AddInParameter(updateCommand, "@PaymentGatewayTemplateId", System.Data.DbType.Int32, this.PaymentGatewayTemplateId);

                        database.AddInParameter(updateCommand, "@Name", System.Data.DbType.String, this.Name);


                        //RESULT IS NUMBER OF RECORDS AFFECTED
                        result = database.ExecuteNonQuery(updateCommand);
                    }
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO xm_PaymentGatewayTemplates (Name )");
                    insertQuery.Append(" VALUES (@Name )");


                    insertQuery.Append("; SELECT @@IDENTITY");


                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {

                        database.AddInParameter(insertCommand, "@PaymentGatewayTemplateId", System.Data.DbType.Int32, this.PaymentGatewayTemplateId);

                        database.AddInParameter(insertCommand, "@Name", System.Data.DbType.String, this.Name);

                        //RESULT IS NUMBER OF RECORDS AFFECTED;
                        result = database.ExecuteNonQuery(insertCommand);


                        this.PaymentGatewayTemplateId = result;


                    }
                }
                MakerShop.Stores.AuditEventDataSource.AuditInfoEnd(); 
                //OBJECT IS DIRTY IF NO RECORDS WERE UPDATED OR INSERTED
                this.IsDirty = (result == 0);
                if (this.IsDirty) { return SaveResult.Failed; }
                else { return (recordExists ? SaveResult.RecordUpdated : SaveResult.RecordInserted); }
            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

        #endregion
    }
}
