//Generated by PersistableBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Marketing;
using MakerShop.Products;
using MakerShop.Utility;

namespace MakerShop.Marketing
{
    /// <summary>
    /// This class represents a CouponProduct object in the database.
    /// </summary>
    public partial class CouponProduct : IPersistable
    {

#region Constructors

        /// <summary>
        /// Default Constructor
        /// </summary>
        public CouponProduct() { }

        /// <summary>
        /// Constructor with primary key
        /// <param name="couponId">Value of CouponId.</param>
        /// <param name="productId">Value of ProductId.</param>
        /// </summary>
        public CouponProduct(Int32 couponId, Int32 productId)
        {
            this.CouponId = couponId;
            this.ProductId = productId;
        }

        /// <summary>
        /// Returns a coma separated list of column names in this database object.
        /// </summary>
        /// <param name="prefix">Prefix to use with column names. Leave null or empty for no prefix.</param>
        /// <returns>A coman separated list of column names for this database object.</returns>
        public static string GetColumnNames(string prefix)
        {
          if (string.IsNullOrEmpty(prefix)) prefix = string.Empty;
          else prefix = prefix + ".";
          List<string> columnNames = new List<string>();
          columnNames.Add(prefix + "CouponId");
          columnNames.Add(prefix + "ProductId");
          return string.Join(",", columnNames.ToArray());
        }

        /// <summary>
        /// Loads the given CouponProduct object from the given database data reader.
        /// </summary>
        /// <param name="couponProduct">The CouponProduct object to load.</param>
        /// <param name="dr">The database data reader to read data from.</param>
        public static void LoadDataReader(CouponProduct couponProduct, IDataReader dr)
        {
            //SET FIELDS FROM ROW DATA
            couponProduct.CouponId = dr.GetInt32(0);
            couponProduct.ProductId = dr.GetInt32(1);
            couponProduct.IsDirty = false;
        }

#endregion

        private Int32 _CouponId;
        private Int32 _ProductId;
        private bool _IsDirty;

        /// <summary>
        /// CouponId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 CouponId
        {
            get { return this._CouponId; }
            set
            {
                if (this._CouponId != value)
                {
                    this._CouponId = value;
                    this.IsDirty = true;
                    this._Coupon = null;
                }
            }
        }

        /// <summary>
        /// ProductId
        /// </summary>
        [DataObjectField(true, false, false)]
        public Int32 ProductId
        {
            get { return this._ProductId; }
            set
            {
                if (this._ProductId != value)
                {
                    this._ProductId = value;
                    this.IsDirty = true;
                    this._Product = null;
                }
            }
        }

        /// <summary>
        /// Indicates whether this CouponProduct object has changed since it was loaded from the database.
        /// </summary>
        public bool IsDirty
        {
            get { return this._IsDirty; }
            set { this._IsDirty = value; }
        }

#region Parents
        private Coupon _Coupon;
        private Product _Product;

        /// <summary>
        /// The Coupon object that this CouponProduct object is associated with
        /// </summary>
        public Coupon Coupon
        {
            get
            {
                if (!this.CouponLoaded)
                {
                    this._Coupon = CouponDataSource.Load(this.CouponId);
                }
                return this._Coupon;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool CouponLoaded { get { return ((this._Coupon != null) && (this._Coupon.CouponId == this.CouponId)); } }

        /// <summary>
        /// The Product object that this CouponProduct object is associated with
        /// </summary>
        public Product Product
        {
            get
            {
                if (!this.ProductLoaded)
                {
                    this._Product = ProductDataSource.Load(this.ProductId);
                }
                return this._Product;
            }
        }

        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal bool ProductLoaded { get { return ((this._Product != null) && (this._Product.ProductId == this.ProductId)); } }

#endregion

        /// <summary>
        /// Deletes this CouponProduct object from the database.
        /// </summary>
        /// <returns><b>true</b> if delete successful, <b>false</b> otherwise.</returns>
        public virtual bool Delete()
        {
            int recordsAffected = 0;
            StringBuilder deleteQuery = new StringBuilder();
            deleteQuery.Append("DELETE FROM ac_CouponProducts");
            deleteQuery.Append(" WHERE CouponId = @couponId AND ProductId = @productId");
            Database database = Token.Instance.Database;
            MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
            using (DbCommand deleteCommand = database.GetSqlStringCommand(deleteQuery.ToString()))
            {
                database.AddInParameter(deleteCommand, "@CouponId", System.Data.DbType.Int32, this.CouponId);
                database.AddInParameter(deleteCommand, "@ProductId", System.Data.DbType.Int32, this.ProductId);
                recordsAffected = database.ExecuteNonQuery(deleteCommand);
            }

            MakerShop.Stores.AuditEventDataSource.AuditInfoEnd();
            return (recordsAffected > 0);
        }

        /// <summary>
        /// Load this CouponProduct object from the database for the given primary key.
        /// </summary>
        /// <param name="couponId">Value of CouponId of the object to load.</param>
        /// <param name="productId">Value of ProductId of the object to load.</param>
        /// <returns><b>true</b> if load is successful, <b>false</b> otherwise</returns>
        public virtual bool Load(Int32 couponId, Int32 productId)
        {
            this.CouponId = couponId;
            this.ProductId = productId;
            this.IsDirty = false;
            return true;
        }

        /// <summary>
        /// Saves this CouponProduct object to the database.
        /// </summary>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        public virtual SaveResult Save()
        {
            if (this.IsDirty)
            {
                Database database = Token.Instance.Database;
                
                bool recordExists = true;
                
                //generate key(s) if needed
                if (recordExists) {
                    //verify whether record is already present
                    StringBuilder selectQuery = new StringBuilder();
                    selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) As RecordCount FROM ac_CouponProducts");
                    selectQuery.Append(" WHERE CouponId = @couponId AND ProductId = @productId");
                    using (DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString()))
                    {
                        database.AddInParameter(selectCommand, "@CouponId", System.Data.DbType.Int32, this.CouponId);
                        database.AddInParameter(selectCommand, "@ProductId", System.Data.DbType.Int32, this.ProductId);
                        if ((int)database.ExecuteScalar(selectCommand) == 0)
                        {
                            recordExists = false;
                        }
                    }
                }

                if (recordExists)
                {
                    //RECORD ALREADY EXISTS IN DATABASE
                    this.IsDirty = false;
                    return SaveResult.RecordUpdated;
                }
                else
                {
                    //INSERT
                    StringBuilder insertQuery = new StringBuilder();
                    insertQuery.Append("INSERT INTO ac_CouponProducts (CouponId, ProductId)");
                    insertQuery.Append(" VALUES (@CouponId, @ProductId)");
                    using (DbCommand insertCommand = database.GetSqlStringCommand(insertQuery.ToString()))
                    {
                        database.AddInParameter(insertCommand, "@CouponId", System.Data.DbType.Int32, this.CouponId);
                        database.AddInParameter(insertCommand, "@ProductId", System.Data.DbType.Int32, this.ProductId);
                        
                        MakerShop.Stores.AuditEventDataSource.AuditInfoBegin(null); 
                        int recordsAffected = database.ExecuteNonQuery(insertCommand);
                        MakerShop.Stores.AuditEventDataSource.AuditInfoEnd(); 

                        //OBJECT IS NOT DIRTY IF RECORD WAS INSERTED
                        this.IsDirty = (recordsAffected == 0);
                        if (this.IsDirty) { return SaveResult.Failed; }
                        return SaveResult.RecordInserted;
                    }
                }

            }

            //SAVE IS SUCCESSFUL IF OBJECT IS NOT DIRTY
            return SaveResult.NotDirty;
        }

     }
}
