//Generated by DataSourceBaseGenerator

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Text;
using MakerShop.Common;
using MakerShop.Data;
using MakerShop.Utility;

namespace MakerShop.Orders
{
    /// <summary>
    /// DataSource class for BasketItem objects
    /// </summary>
    public partial class BasketItemDataSource
    {
        /// <summary>
        /// Deletes a BasketItem object from the database
        /// </summary>
        /// <param name="basketItem">The BasketItem object to delete</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static bool Delete(BasketItem basketItem)
        {
            return basketItem.Delete();
        }

        /// <summary>
        /// Deletes a BasketItem object with given id from the database
        /// </summary>
        /// <param name="basketItemId">Value of BasketItemId of the object to delete.</param>
        /// <returns><b>true</b> if delete operation is successful, <b>false</b> otherwise</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Delete)]
        public static bool Delete(Int32 basketItemId)
        {
            BasketItem basketItem = new BasketItem();
            if (basketItem.Load(basketItemId)) return basketItem.Delete();
            return false;
        }

        /// <summary>
        /// Inserts/Saves a BasketItem object to the database.
        /// </summary>
        /// <param name="basketItem">The BasketItem object to insert</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Insert)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Insert(BasketItem basketItem) { return basketItem.Save(); }

        /// <summary>
        /// Loads a BasketItem object for given Id from the database.
        /// </summary>
        /// <param name="basketItemId">Value of BasketItemId of the object to load.</param>
        /// <returns>If the load is successful the newly loaded BasketItem object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItem Load(Int32 basketItemId)
        {
            return BasketItemDataSource.Load(basketItemId, true);
        }

        /// <summary>
        /// Loads a BasketItem object for given Id from the database.
        /// </summary>
        /// <param name="basketItemId">Value of BasketItemId of the object to load.</param>
        /// <param name="useCache">If true tries to load object from cache first.</param>
        /// <returns>If the load is successful the newly loaded BasketItem object is returned. If load fails null is returned.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItem Load(Int32 basketItemId, bool useCache)
        {
            if (basketItemId == 0) return null;
            BasketItem basketItem = null;
            string key = "BasketItem_" + basketItemId.ToString();
            if (useCache)
            {
                basketItem = ContextCache.GetObject(key) as BasketItem;
                if (basketItem != null) return basketItem;
            }
            basketItem = new BasketItem();
            if (basketItem.Load(basketItemId))
            {
                if (useCache) ContextCache.SetObject(key, basketItem);
                return basketItem;
            }
            return null;
        }

        /// <summary>
        /// Counts the number of BasketItem objects in result if retrieved using the given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the BasketItem objects that should be loaded.</param>
        /// <returns>The number of BasketItem objects matching the criteria</returns>
        public static int CountForCriteria(string sqlCriteria)
        {
            Database database = Token.Instance.Database;
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems" + whereClause);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForCriteria(string sqlCriteria)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForCriteria(string sqlCriteria, string sortExpression)
        {
            return LoadForCriteria(sqlCriteria, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex)
        {
            return LoadForCriteria(sqlCriteria, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects from the database based on given SQL criteria
        /// </summary>
        /// <param name="sqlCriteria">The SQL criteria string that determines the objects that should be loaded.</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection  LoadForCriteria(string sqlCriteria, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            string whereClause = string.IsNullOrEmpty(sqlCriteria) ? string.Empty : " WHERE " + sqlCriteria;
            selectQuery.Append(whereClause);
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItem objects for the given BasketId in the database.
        /// <param name="basketId">The given BasketId</param>
        /// </summary>
        /// <returns>The Number of BasketItem objects for the given BasketId in the database.</returns>
        public static int CountForBasket(Int32 basketId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems WHERE BasketId = @basketId");
            database.AddInParameter(selectCommand, "@basketId", System.Data.DbType.Int32, basketId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given BasketId from the database
        /// </summary>
        /// <param name="basketId">The given BasketId</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForBasket(Int32 basketId)
        {
            return LoadForBasket(basketId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given BasketId from the database
        /// </summary>
        /// <param name="basketId">The given BasketId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForBasket(Int32 basketId, string sortExpression)
        {
            return LoadForBasket(basketId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given BasketId from the database
        /// </summary>
        /// <param name="basketId">The given BasketId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForBasket(Int32 basketId, int maximumRows, int startRowIndex)
        {
            return LoadForBasket(basketId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given BasketId from the database
        /// </summary>
        /// <param name="basketId">The given BasketId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForBasket(Int32 basketId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            selectQuery.Append(" WHERE BasketId = @basketId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@basketId", System.Data.DbType.Int32, basketId);
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItem objects for the given ProductId in the database.
        /// <param name="productId">The given ProductId</param>
        /// </summary>
        /// <returns>The Number of BasketItem objects for the given ProductId in the database.</returns>
        public static int CountForProduct(Int32 productId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems WHERE ProductId = @productId");
            database.AddInParameter(selectCommand, "@productId", System.Data.DbType.Int32, productId);
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given ProductId from the database
        /// </summary>
        /// <param name="productId">The given ProductId</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForProduct(Int32 productId)
        {
            return LoadForProduct(productId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given ProductId from the database
        /// </summary>
        /// <param name="productId">The given ProductId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForProduct(Int32 productId, string sortExpression)
        {
            return LoadForProduct(productId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given ProductId from the database
        /// </summary>
        /// <param name="productId">The given ProductId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForProduct(Int32 productId, int maximumRows, int startRowIndex)
        {
            return LoadForProduct(productId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given ProductId from the database
        /// </summary>
        /// <param name="productId">The given ProductId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForProduct(Int32 productId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            selectQuery.Append(" WHERE ProductId = @productId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@productId", System.Data.DbType.Int32, productId);
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItem objects for the given TaxCodeId in the database.
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// </summary>
        /// <returns>The Number of BasketItem objects for the given TaxCodeId in the database.</returns>
        public static int CountForTaxCode(Int32 taxCodeId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems WHERE TaxCodeId = @taxCodeId");
            database.AddInParameter(selectCommand, "@taxCodeId", System.Data.DbType.Int32, NullableData.DbNullify(taxCodeId));
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForTaxCode(Int32 taxCodeId)
        {
            return LoadForTaxCode(taxCodeId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForTaxCode(Int32 taxCodeId, string sortExpression)
        {
            return LoadForTaxCode(taxCodeId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForTaxCode(Int32 taxCodeId, int maximumRows, int startRowIndex)
        {
            return LoadForTaxCode(taxCodeId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given TaxCodeId from the database
        /// </summary>
        /// <param name="taxCodeId">The given TaxCodeId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForTaxCode(Int32 taxCodeId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            selectQuery.Append(" WHERE TaxCodeId = @taxCodeId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@taxCodeId", System.Data.DbType.Int32, NullableData.DbNullify(taxCodeId));
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItem objects for the given WishlistItemId in the database.
        /// <param name="wishlistItemId">The given WishlistItemId</param>
        /// </summary>
        /// <returns>The Number of BasketItem objects for the given WishlistItemId in the database.</returns>
        public static int CountForWishlistItem(Int32 wishlistItemId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems WHERE WishlistItemId = @wishlistItemId");
            database.AddInParameter(selectCommand, "@wishlistItemId", System.Data.DbType.Int32, NullableData.DbNullify(wishlistItemId));
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WishlistItemId from the database
        /// </summary>
        /// <param name="wishlistItemId">The given WishlistItemId</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWishlistItem(Int32 wishlistItemId)
        {
            return LoadForWishlistItem(wishlistItemId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WishlistItemId from the database
        /// </summary>
        /// <param name="wishlistItemId">The given WishlistItemId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWishlistItem(Int32 wishlistItemId, string sortExpression)
        {
            return LoadForWishlistItem(wishlistItemId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WishlistItemId from the database
        /// </summary>
        /// <param name="wishlistItemId">The given WishlistItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWishlistItem(Int32 wishlistItemId, int maximumRows, int startRowIndex)
        {
            return LoadForWishlistItem(wishlistItemId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WishlistItemId from the database
        /// </summary>
        /// <param name="wishlistItemId">The given WishlistItemId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWishlistItem(Int32 wishlistItemId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            selectQuery.Append(" WHERE WishlistItemId = @wishlistItemId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@wishlistItemId", System.Data.DbType.Int32, NullableData.DbNullify(wishlistItemId));
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Counts the number of BasketItem objects for the given WrapStyleId in the database.
        /// <param name="wrapStyleId">The given WrapStyleId</param>
        /// </summary>
        /// <returns>The Number of BasketItem objects for the given WrapStyleId in the database.</returns>
        public static int CountForWrapStyle(Int32 wrapStyleId)
        {
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT COUNT(1) AS TotalRecords FROM ac_BasketItems WHERE WrapStyleId = @wrapStyleId");
            database.AddInParameter(selectCommand, "@wrapStyleId", System.Data.DbType.Int32, NullableData.DbNullify(wrapStyleId));
            return MakerShop.Utility.AlwaysConvert.ToInt(database.ExecuteScalar(selectCommand));
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WrapStyleId from the database
        /// </summary>
        /// <param name="wrapStyleId">The given WrapStyleId</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWrapStyle(Int32 wrapStyleId)
        {
            return LoadForWrapStyle(wrapStyleId, 0, 0, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WrapStyleId from the database
        /// </summary>
        /// <param name="wrapStyleId">The given WrapStyleId</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWrapStyle(Int32 wrapStyleId, string sortExpression)
        {
            return LoadForWrapStyle(wrapStyleId, 0, 0, sortExpression);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WrapStyleId from the database
        /// </summary>
        /// <param name="wrapStyleId">The given WrapStyleId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWrapStyle(Int32 wrapStyleId, int maximumRows, int startRowIndex)
        {
            return LoadForWrapStyle(wrapStyleId, maximumRows, startRowIndex, string.Empty);
        }

        /// <summary>
        /// Loads a collection of BasketItem objects for the given WrapStyleId from the database
        /// </summary>
        /// <param name="wrapStyleId">The given WrapStyleId</param>
        /// <param name="maximumRows">Maximum number of rows to retrieve.</param>
        /// <param name="startRowIndex">Starting index from where to start retrieving.</param>
        /// <param name="sortExpression">The sort expression to use for sorting the loaded objects.</param>
        /// <returns>A collection of BasketItem objects</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Select)]
        public static BasketItemCollection LoadForWrapStyle(Int32 wrapStyleId, int maximumRows, int startRowIndex, string sortExpression)
        {
            //DEFAULT SORT EXPRESSION
            if (string.IsNullOrEmpty(sortExpression)) sortExpression = "OrderBy";
            //CREATE THE DYNAMIC SQL TO LOAD OBJECT
            StringBuilder selectQuery = new StringBuilder();
            selectQuery.Append("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT");
            if (maximumRows > 0) selectQuery.Append(" TOP " + (startRowIndex + maximumRows).ToString());
            selectQuery.Append(" " + BasketItem.GetColumnNames(string.Empty));
            selectQuery.Append(" FROM ac_BasketItems");
            selectQuery.Append(" WHERE WrapStyleId = @wrapStyleId");
            selectQuery.Append(" ORDER BY " + sortExpression);
            Database database = Token.Instance.Database;
            DbCommand selectCommand = database.GetSqlStringCommand(selectQuery.ToString());
            database.AddInParameter(selectCommand, "@wrapStyleId", System.Data.DbType.Int32, NullableData.DbNullify(wrapStyleId));
            //EXECUTE THE COMMAND
            BasketItemCollection results = new BasketItemCollection();
            int thisIndex = 0;
            int rowCount = 0;
            using (IDataReader dr = database.ExecuteReader(selectCommand))
            {
                while (dr.Read() && ((maximumRows < 1) || (rowCount < maximumRows)))
                {
                    if (thisIndex >= startRowIndex)
                    {
                        BasketItem basketItem = new BasketItem();
                        BasketItem.LoadDataReader(basketItem, dr);
                        results.Add(basketItem);
                        rowCount++;
                    }
                    thisIndex++;
                }
                dr.Close();
            }
            return results;
        }

        /// <summary>
        /// Gets the next value of the OrderBy field for BasketItem objects.
        /// </summary>
        /// <param name="basketId">The BasketId for which to get the next OrderBy value</param>
        /// <returns>The next value of the OrderBy field for BasketItem objects</returns>
        public static short GetNextOrderBy(Int32 basketId)
        {
            Database database = Token.Instance.Database;
            using (DbCommand selectCommand = database.GetSqlStringCommand("SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; SELECT (Max(OrderBy) + 1) AS NextOrderBy FROM ac_BasketItems WHERE BasketId = @basketId"))
            {
                database.AddInParameter(selectCommand, "@basketId", System.Data.DbType.Int32, basketId);
                object result = database.ExecuteScalar(selectCommand);
                if (result.Equals(DBNull.Value)) return 1;
                return (short)(int)result;
            }
        }

        /// <summary>
        /// Updates/Saves the given BasketItem object to the database.
        /// </summary>
        /// <param name="basketItem">The BasketItem object to update/save to database.</param>
        /// <returns><b>SaveResult</b> enumeration that represents the result of the save operation.</returns>
        [System.ComponentModel.DataObjectMethod(System.ComponentModel.DataObjectMethodType.Update)]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
        public static SaveResult Update(BasketItem basketItem) { return basketItem.Save(); }

    }
}
